
spring:
  application:
    name: user-service

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    url: ${DB_URL:jdbc:postgresql://localhost:9000/pg_db}
    user: ${DB_USER:admin}
    password: ${DB_PASS:admin}
    enabled: true
    default-schema: user_management
    liquibase-schema: user_management_migrations

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:9000/pg_db}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${spring.liquibase.default-schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    ru.puchinets.userservice.controller.rest: trace
    ru.puchinets.userservice.service.impl: trace
  file:
    name: user-service.log
    path: /logs/user-service/

server:
  port: 9001
springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html
